### ISSUE TITLE
des加密解密和java的des加密解密不一致

### ISSUE THREAD

**Issue by yutons** [baiy/chrome-tool#2]
java加密后你的工具无法解密

**Comment by baiy** [comment]
由于des加密有较多的参数设置,当前工具只提供有限的参数设置  确实会出现无法解密的情况

就当前参数设置而言，于`http://tool.chinaz.com/tools/textencrypt.aspx`和`http://tool.oschina.net/encrypt/`对比来看, 解密结果是正确的

可以确认一下参数设置

**Comment by yutons** [comment]
那当前插件如何修改MODE, key, iv参数呢?

**Comment by baiy** [comment]
当前插件暂时不支持更多的参数设置 只提供最基本的功能
如需要更多功能可以使用下面的网站试试
> http://tool.chacuo.net/cryptdes
