### ISSUE TITLE
序列化

### ISSUE THREAD

**Issue by qq1027507634** [baiy/chrome-tool#5]
支持字符串序列化

**Comment by baiy** [comment]
请详细描述一下

**Comment by declandragon** [comment]
array('a' => 1, 'b' => 2);
"a:2:{s:1:"a";i:1;s:1:"b";i:2;}"

**Comment by declandragon** [comment]
array('a' => 1, 'b' => 2);
"a:2:{s:1:"a";i:1;s:1:"b";i:2;}"
serialize
php序列化反序列化

**Comment by baiy** [comment]
已经添加支持
